conf:
  enable:
    debug: false
  change:
    displayname: true
    tabname: true
    chat: true
    quit: true
    join: true
  disable:
    join: false
    quit: false
    chat: false
    
formats:
  chat: "&a%PLAYER%&7: %MESSAGE%"

messages:
  quitmsg: "&c- &7%PLAYER% &7left the game"
  joinmsg: "&a+ &7%PLAYER% &7joined the game"